---
- hosts: all
  vars:
   ansible_ssh_private_key_file: ~/.ssh/id_ed25519 
  become: true
  pre_tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

- hosts: Supervisor
  become: true
  roles:
    - Supervisor

- hosts: Employee
  become: true
  roles:
    - Employee
